name: build-staging
jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Install bundler
        run: |
          gem install bundler:2.1.4
      - name: Cache rubygems
        uses: actions/cache@v2
        with:
          path: |
            ./bundle
          key: ${{ runner.os }}-${{ hashFiles('Gemfile.lock') }}
      - name: Bundle Build
        id: bundlebuild
        run: |
          bundle install --path ./bundle
      - name: Build
        id: build
        run: |
          bundle exec middleman build
on:
  push:
    branches:
      - master
